name: Executable

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: python -m pip install -r requirements.txt
      - run: python -m PyInstaller --onefile --noconsole app
      - uses: actions/upload-artifact@v2
        with:
          name: app
          path: dist/app

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v2
        with:
          name: app
          path: dist
      - run: chmod +x dist/app
      - run: pushd dist && tar -pczvf app.tar.gz app && popd
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/app.tar.gz
          asset_name: app_standalone_linux-x64.tar.gz
          asset_content_type: application/octet-stream
